### ISSUE TITLE
Document all the CI jobs in .yml files and autogenerate docs

### ISSUE THREAD

**Issue by grdddj** [trezor/trezor-firmware#2064]
Currently we have very little documentation on `CI`, mostly for the `build` and `test` stage (here https://github.com/trezor/trezor-firmware/blob/master/docs/ci/jobs.md) - a lot of jobs are undocumented.

We could put desciptions in the `.yml` test files themselves, connected with all the tests, and then somehow extract these things into `jobs.md` file.

Possibility:
```yml
## Build of our cryptographic library, which is then incorporated into the other builds.
crypto build:
  stage: build
  <<: *gitlab_caching
  ......

## Build of Legacy into UNIX emulator. Use keyboard arrows to emulate button presses.
## Bitcoin-only version.
legacy emu btconly debug build:
  stage: build
  <<: *gitlab_caching
  ........
```

Then having some script to go through all job definitions (`crypto build`, `legacy emu btconly debug build`, etc. - the only things in file that are not indented), grabbing the comment above them and writing it into a markdown file

The above would generate something like this into the markdown file
```md
### crypto build
Build of our cryptographic library, which is then incorporated into the other builds.

### legacy emu btconly debug build
Build of Legacy into UNIX emulator. Use keyboard arrows to emulate button presses.
Bitcoin-only version.
```
