### ISSUE TITLE
Make T1/TR screenshots larger in test reports

### ISSUE THREAD

**Issue by matejcik** [trezor/trezor-firmware#2290]
When generating the HTML report, it would be useful to 2x upscale the images coming from the small T1 / TR screens.

the following CSS works for me:
```css
img {
   width: 256px;
   image-rendering: pixelated;
}
```
